# Numpy
- Numpy is a general purpose array-processing package. It provides a high-performance multidimensional array object and tools for working with these arrays.It is the fundamental package for scientific computing with python.

# What is an array
- An array is a data structure that stores values of same data type. In python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data types.

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
## Initially lets import numpy as a library

import numpy as np

In [3]:
my_list = [1,2,3,4,5]

arr = np.array(my_list) #one-dimensioned array

In [4]:
type(arr)

numpy.ndarray

In [5]:
arr

array([1, 2, 3, 4, 5])

In [6]:
arr.shape # shape helps to identify how many no of rows and columns do we have

# if it is a one-dimensioned array then basically it will just say how many no of elements in array it is

(5,)

In [19]:
## multi-dimensioned array

my_list1 = [1,2,3,4,5]
my_list2 = [2,3,4,5,6]
my_list3 = [9,7,6,5,4]

arr1 = np.array([my_list1,my_list2,my_list3]) #in twodimensioned array we have 2 [[]] open and closed brackets

In [20]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 5, 4]])

In [9]:
arr1.shape

(3, 5)

In [10]:
arr1.reshape(5,3) #change the no of rows and columns

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 9, 7],
       [6, 5, 4]])

In [11]:
arr1.reshape(5,4) # not possible as total no of elements should be 15(3 * 5 = 15)

ValueError: cannot reshape array of size 15 into shape (5,4)

# Indexing

In [22]:
arr2 = np.array([1,2,3,4,5,6,7,8,9])

In [23]:
arr2[3]

4

In [24]:
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
arr1 #row 1 is 0th index, row 2 1st index ...

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 5, 4]])

In [25]:
arr1[1,3] , 2nd row and 4th 

5

In [26]:
arr1[:,:] #take all the values from rows and clms

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 5, 4]])

In [27]:
arr1[0:2,] # i want 0th index to n-1 = 1 index rows values

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

In [28]:
arr1[0:2,0:2]

array([[1, 2],
       [2, 3]])

In [29]:
arr1[1:3,3:5] # or we can write like this also arr1[1:,3:]

array([[5, 6],
       [5, 4]])

In [30]:
arr3 = np.arange(0,10)

In [31]:
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
np.linspace(1,10,50) # between 1 and 10 i need 50 points

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [32]:
#copy function and broadcasting

arr3[3:] = 100
arr3

array([  0,   1,   2, 100, 100, 100, 100, 100, 100, 100])

In [34]:
arr4 = np.arange(0,10,step=3) #gap of 3 

In [35]:
arr4 

array([0, 3, 6, 9])

In [37]:
arr5 = arr3

In [38]:
arr5[3:] = 500
print(arr5)

[  0   1   2 500 500 500 500 500 500 500]


In [39]:
arr3 # arr3 has been reassigned by arr5

array([  0,   1,   2, 500, 500, 500, 500, 500, 500, 500])

In [40]:
arr5 = arr3.copy()

In [41]:
# copy - created another memory space to store value of arr3

print(arr3)
arr5[3:] = 1000
print(arr5) 

[  0   1   2 500 500 500 500 500 500 500]
[   0    1    2 1000 1000 1000 1000 1000 1000 1000]


In [47]:
## Some consitions very useful in explonatory data analysis

val = 2
arr3[arr3 < val]

array([0, 1])

In [48]:
## Create arrays and reshape

np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [49]:
arr6 = np.arange(0,10).reshape(2,5)

In [50]:
arr7 = np.arange(0,10).reshape(2,5)

In [51]:
arr6 * arr7

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [52]:
## np.ones - creates an array which basically replace all elements by 1

np.ones(4) #bydefault dtype is flot thatswhy here its coming as 1. instead of 1

array([1., 1., 1., 1.])

In [53]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [54]:
np.ones((2,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [55]:
## random distribution

np.random.rand(3,3) #based on uniform distribution

array([[0.31556076, 0.35539807, 0.03476701],
       [0.10483245, 0.03029695, 0.77366761],
       [0.57469525, 0.28111549, 0.51627614]])

In [56]:
arr_ex = np.random.randn(4,4) #select random variable based on standard normal distribution

In [57]:
arr_ex

array([[ 2.0432875 ,  0.41418816, -0.02158548,  0.55519502],
       [-0.55475918, -0.23019673,  0.38309347,  0.51796196],
       [ 1.90235901,  0.88402966, -0.2383721 ,  0.57795773],
       [ 1.09290358,  0.41859059,  0.92726552,  0.2646122 ]])

In [59]:
np.random.randint(0,100,8).reshape(4,2) #between 0 to 100 range select 8 numbers

array([[49, 41],
       [26, 50],
       [41, 14],
       [87, 69]])

In [60]:
np.random.random_sample((1,5)) #return random floats in the half-open interval[0.0, 1.0]

array([[0.8963837 , 0.78111075, 0.47686157, 0.93261199, 0.76682847]])